export const ADD_ITEM_TO_BASKET = 'ADD_ITEM_TO_BASKET';
export const DELETE_ITEM_FROM_BASKET = 'DELETE_ITEM_FROM_BASKET';
export const CHANGE_SEQUENCE_BASKET = 'CHANGE_SEQUENCE_BASKET';
export const SET_CURRENT_DRAG_ITEM = 'SET_CURRENT_DRAG_ITEM';
